version: '3.9'
services:
  postgres-db:
    image: postgres:15
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: busify
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - busify-test-network
  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --requirepass ${REDIS_PASSWORD} --loglevel warning
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - busify-test-network

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - '6379:6379'
      - '8001:8001'
    environment:
      REDIS_ARGS: "--loglevel warning"
    networks:
      - busify-test-network
networks:
  busify-test-network:
     driver: bridge

volumes:
  postgres-data:
  # redis-data: